/* Database schema to keep the structure of entire database. */

create table animals (
	id serial,
	name varchar(45),
	date_of_birth date,
	escape_attempts integer,
	neutered boolean,
  	weight_kg decimal(10,4),
  	species varchar(45),
	PRIMARY KEY(id)
);

create table owners (
	owner_id int generated by default as identity,
	full_name varchar(45),
	age int, 
	primary key(owner_id)
);

create table species (
	id int generated by default as identity,
	name varchar(45),
	primary key(id)
);